# -*- coding: utf-8 -*-
"""BinearClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EztnvWNiVH8PV-1mfNOoFy_p_IEGwbBZ
"""

# # TensorFlow and tf.keras
# import tensorflow as tf
# # from PIL import Image
# import os
# import seaborn as sns


# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import cv2
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
# uploaded = files.upload()
img = plt.imread('/content/2_100.jpg')
plt.imshow(img)

os.chdir("/content/drive/MyDrive/Training-Pineapple")
!ls

os.getcwd()  # return name of current directory
os.listdir()  # return list of files in directory

files = []
for i in range(1):
    files=[i for i in os.listdir() if os.path.isfile(i)]
    print(files)
    # Get the MD5 hash for each -- use a for loop to process each file
    # for file_name in files:

for i, j in enumerate(files[:100]):
    img = plt.imread('/content/drive/MyDrive/Training-Pineapple/' + j)
    plt.subplot(10,10,i+1)
    # plt.figure(figsize=(50,50))/
    plt.title(j.split('.')[0])
    plt.axis('off')
    plt.imshow(img)

train_prickle_dir = "/content/drive/MyDrive/Training-Pineapple"

classes = ['Blue_one', 'Prickly_one']
img_size = 100
train_ararys = []

for img in os.listdir(os.getcwd()):
    img_arr =  cv2.imread(os.path.join(os.getcwd(), img))
    img_arr = cv2.cvtColor(img_arr, cv2.COLOR_BGR2RGB)
    train_ararys.append([img_arr, classes[1]])

only_img_list = []
for image, c_count in train_ararys:
    only_img_list.append(image)

# print(only_img_list[0][0])
# magick(only_img_list[0])

from IPython.core.pylabtools import figsize
def magick(ananasaaaa):
    # plt.subplot(figsize=(8,8))
    plt.imshow(ananasaaaa)
    plt.axis('off')

train_prickle_dir = "/content/drive/MyDrive/Training-Pineapple"
train_huck_dir = "/content/drive/MyDrive/Training-Huckleberry"
test_prickle_dir = "/content/drive/MyDrive/Test-Pineapple"
test_huck_dir = "/content/drive/MyDrive/Test-Huckleberry"

directory = [train_prickle_dir, train_huck_dir, test_prickle_dir, test_huck_dir]
classes = ['Blue_one', 'Prickly_one']
img_size = 100
train_ararys = []
test_ararys = []

for i in classes:
    for k in range(4):
        path  = os.path.join(directory[k], i)  # its return a fucking string with path and class type
        for img in os.listdir(path):
            img_arr =  cv2.imread(os.path.join(path, img))
            img_arr = cv2.cvtColor(img_arr, cv2.COLOR_BRG2RGB)
            if i == 0:
                train_ararys.append([img_arr, i])
            else:
                test_ararys.append([img_arr, i])

only_img_list = []
for image, c_count in train_ararys:
    only_img_list.append(image)